name: ml-lint
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Update version as needed
      - name: Install dependencies
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Lint with pylint
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          pylint **/*.py
      - name: Format with black
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          black --diff --check **/*.py
